package wordcounter;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aryan Mehta
 */
public class fileSelecter extends javax.swing.JFrame {

    public fileSelecter() {
        initComponents();
        init();
    }

    private void init() {
        isFileSelected = 0;
    }

    //global variables
    int isFileSelected = 0;
    ArrayList<String> wordList;
    String delimiters = "[ ,\n\t;:]";
    File in_file;
    String in_lines = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_pan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_ta_info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_textIN = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        bt_selectFIle = new javax.swing.JButton();
        but_prosText = new javax.swing.JButton();
        lbl_fileName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Word Processor");
        setResizable(false);

        main_pan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Word Counter");
        jLabel1.setOpaque(true);

        lbl_ta_info.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ta_info.setText("Enter Text:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ta_textIN.setColumns(20);
        ta_textIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ta_textIN.setRows(5);
        ta_textIN.setToolTipText("Enter Text");
        jScrollPane1.setViewportView(ta_textIN);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("OR");

        bt_selectFIle.setBackground(new java.awt.Color(0, 0, 0));
        bt_selectFIle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_selectFIle.setForeground(new java.awt.Color(255, 255, 255));
        bt_selectFIle.setText("Select Word File");
        bt_selectFIle.setFocusPainted(false);
        bt_selectFIle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_selectFIleActionPerformed(evt);
            }
        });

        but_prosText.setBackground(new java.awt.Color(0, 0, 0));
        but_prosText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_prosText.setForeground(new java.awt.Color(255, 255, 255));
        but_prosText.setText("Process Text");
        but_prosText.setFocusPainted(false);
        but_prosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_prosTextActionPerformed(evt);
            }
        });

        lbl_fileName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout main_panLayout = new javax.swing.GroupLayout(main_pan);
        main_pan.setLayout(main_panLayout);
        main_panLayout.setHorizontalGroup(
            main_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panLayout.createSequentialGroup()
                        .addComponent(lbl_ta_info, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(main_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panLayout.createSequentialGroup()
                                .addComponent(bt_selectFIle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panLayout.createSequentialGroup()
                                .addComponent(but_prosText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        main_panLayout.setVerticalGroup(
            main_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(main_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ta_info)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(main_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_fileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_selectFIle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(but_prosText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //select the user inputed file
    private void bt_selectFIleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_selectFIleActionPerformed
        //initialize JFileChooser to select file 
        JFileChooser fileChooser = new JFileChooser();
        ArrayList<String> inLines = new ArrayList<>();

        int response = fileChooser.showSaveDialog(main_pan);

        //if user has select a file
        if (response == JFileChooser.APPROVE_OPTION) {
            //get selected file
            in_file = fileChooser.getSelectedFile();

            try {
                BufferedReader bf = new BufferedReader(new FileReader(in_file));
                String line;

                while ((line = bf.readLine()) != null) {
                    //save the read word in string
                    in_lines += line;
                }
                if (in_lines.equals("")) {
                    JOptionPane.showMessageDialog(null, "Input File is Empty!!");
                } else {
                    ta_textIN.setText(in_lines);
                    lbl_ta_info.setText("Text File :");
                    main_pan.revalidate();
                    isFileSelected = 1;
                    lbl_fileName.setText(in_file.getName());
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Opening the File!!");
            }

        } else if (response == JFileChooser.CANCEL_OPTION) {
            isFileSelected = 0;
        }
    }//GEN-LAST:event_bt_selectFIleActionPerformed

    private void but_prosTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_prosTextActionPerformed
        wordList = new ArrayList<>();
        //if user is asking to process text without any input produce error
        if ((isFileSelected == 0) && ta_textIN.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a text file or add text in the field!!");
        } else {
            //start string processing
            if (isFileSelected == 0) {
                in_lines = ta_textIN.getText();
            }

            String tokens[] = in_lines.split(delimiters);

            for (String line : tokens) {
                wordList.add(line);
            }

            JOptionPane.showMessageDialog(null, "Word Count :" + wordList.size());
        }
    }//GEN-LAST:event_but_prosTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fileSelecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fileSelecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fileSelecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fileSelecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fileSelecter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_selectFIle;
    private javax.swing.JButton but_prosText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fileName;
    private javax.swing.JLabel lbl_ta_info;
    private javax.swing.JPanel main_pan;
    private javax.swing.JTextArea ta_textIN;
    // End of variables declaration//GEN-END:variables
}
