package randomnumbergame;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Aryan Mehta
 */
public class mainApp extends javax.swing.JFrame {

    //global variable decalration
    private int gen_random_num;
    private int user_random_num;
    private int num_dif;
    private int user_tries;
    
    //method to generate random number between range of 1-100
    private void generateNumber(){
        //using java.util.random class to generate random number
        Random random = new Random();
        
        //1 is added in the generated number since the range of random.nextInt is 0-100
        gen_random_num = random.nextInt(100)+1;
    }
    
    /**
     * Creates new form mainApp
     */
    public mainApp() {
        initComponents();
        //random number generator method is called
        generateNumber();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_main = new javax.swing.JPanel();
        bt_retry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_guess = new javax.swing.JTextField();
        bt_guess = new javax.swing.JButton();
        lbl_status = new javax.swing.JLabel();
        lbl_attempts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Guessing Game");
        setResizable(false);

        pan_main.setBackground(new java.awt.Color(255, 255, 255));

        bt_retry.setBackground(new java.awt.Color(0, 0, 204));
        bt_retry.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        bt_retry.setForeground(new java.awt.Color(0, 255, 102));
        bt_retry.setText("R");
        bt_retry.setToolTipText("Restart Game");
        bt_retry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retryActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guess the Correct Number\n");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Your Guess :");

        tf_guess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_guess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_guessActionPerformed(evt);
            }
        });

        bt_guess.setBackground(new java.awt.Color(0, 0, 204));
        bt_guess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_guess.setForeground(new java.awt.Color(0, 255, 102));
        bt_guess.setText("Guess");
        bt_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guessActionPerformed(evt);
            }
        });

        lbl_status.setBackground(new java.awt.Color(0, 0, 204));
        lbl_status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(0, 255, 102));
        lbl_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_status.setOpaque(true);

        lbl_attempts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_attempts.setText("Tries: 0");

        javax.swing.GroupLayout pan_mainLayout = new javax.swing.GroupLayout(pan_main);
        pan_main.setLayout(pan_mainLayout);
        pan_mainLayout.setHorizontalGroup(
            pan_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pan_mainLayout.createSequentialGroup()
                .addGroup(pan_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_mainLayout.createSequentialGroup()
                        .addComponent(lbl_attempts, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)
                        .addComponent(bt_retry))
                    .addGroup(pan_mainLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tf_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bt_guess)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_mainLayout.setVerticalGroup(
            pan_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_mainLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_mainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_attempts))
                    .addComponent(bt_retry, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_guess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //an action event is added for handling the event when user presses guess!!
    private void bt_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guessActionPerformed
        //accept the value from the textfield
        //check if user entered any value or not
        //if textfield is blank produce error
        if((tf_guess.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter A Number!!");
        }
        //else start comparison
        else{
            //increment the attemp counter
            user_tries++;
            
            //string value read is converted to integer
            user_random_num = Integer.valueOf(tf_guess.getText());
            
            //if the entered number is same produce result
            if(user_random_num==gen_random_num){
                lbl_status.setText("Bravo!!You have Guessed the right number :"+gen_random_num);
            //if the guessed number is more than 10 from the generatred number show too high
            }else if(user_random_num>(gen_random_num+10)){
                lbl_status.setText("You have guessed TOO HIGH!");
            //if the guessed number is less than 10 from generated number show too low
            }else if(user_random_num<(gen_random_num-10)){
                lbl_status.setText("You have guessed TOO LOW");
            }else{
                lbl_status.setText("You Are Close!!!");
            }
            lbl_attempts.setText("Tries: "+user_tries);
            pan_main.revalidate();
        }
    }//GEN-LAST:event_bt_guessActionPerformed

    private void tf_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_guessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_guessActionPerformed

    //button to restart the game 
    private void bt_retryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retryActionPerformed
        generateNumber();
        tf_guess.setText("");
        lbl_attempts.setText("Tries:0");
        user_tries=0;
        lbl_status.setText("");
    }//GEN-LAST:event_bt_retryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guess;
    private javax.swing.JButton bt_retry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_attempts;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPanel pan_main;
    private javax.swing.JTextField tf_guess;
    // End of variables declaration//GEN-END:variables
}
