package application_frames;

/**
 *
 * @author Aryan Mehta
 */
public class main_frame extends javax.swing.JFrame {

    public main_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_addCon = new javax.swing.JButton();
        bt_updateCon = new javax.swing.JButton();
        bt_remCon = new javax.swing.JButton();
        bt_srcCon = new javax.swing.JButton();
        bt_disAllCon = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contact Management System");
        jLabel1.setOpaque(true);

        bt_addCon.setBackground(new java.awt.Color(0, 0, 0));
        bt_addCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_addCon.setForeground(new java.awt.Color(255, 255, 255));
        bt_addCon.setText("Add Contact");
        bt_addCon.setFocusPainted(false);
        bt_addCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addConActionPerformed(evt);
            }
        });

        bt_updateCon.setBackground(new java.awt.Color(0, 0, 0));
        bt_updateCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_updateCon.setForeground(new java.awt.Color(255, 255, 255));
        bt_updateCon.setText("Update Contact");
        bt_updateCon.setFocusPainted(false);
        bt_updateCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateConActionPerformed(evt);
            }
        });

        bt_remCon.setBackground(new java.awt.Color(0, 0, 0));
        bt_remCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_remCon.setForeground(new java.awt.Color(255, 255, 255));
        bt_remCon.setText("Remove Contact");
        bt_remCon.setFocusPainted(false);
        bt_remCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_remConActionPerformed(evt);
            }
        });

        bt_srcCon.setBackground(new java.awt.Color(0, 0, 0));
        bt_srcCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_srcCon.setForeground(new java.awt.Color(255, 255, 255));
        bt_srcCon.setText("Find Contact");
        bt_srcCon.setFocusPainted(false);
        bt_srcCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_srcConActionPerformed(evt);
            }
        });

        bt_disAllCon.setBackground(new java.awt.Color(0, 0, 0));
        bt_disAllCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_disAllCon.setForeground(new java.awt.Color(255, 255, 255));
        bt_disAllCon.setText("Display All Contacts");
        bt_disAllCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_disAllConActionPerformed(evt);
            }
        });

        bt_exit.setBackground(new java.awt.Color(0, 0, 0));
        bt_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_exit.setForeground(new java.awt.Color(255, 255, 255));
        bt_exit.setText("Exit");
        bt_exit.setFocusPainted(false);
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(bt_disAllCon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_remCon, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(bt_srcCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_updateCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bt_addCon, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_addCon)
                .addGap(18, 18, 18)
                .addComponent(bt_updateCon)
                .addGap(18, 18, 18)
                .addComponent(bt_remCon)
                .addGap(18, 18, 18)
                .addComponent(bt_srcCon)
                .addGap(18, 18, 18)
                .addComponent(bt_disAllCon)
                .addGap(18, 18, 18)
                .addComponent(bt_exit)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addConActionPerformed
        new addCon_fram().setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_addConActionPerformed

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        dispose();
    }//GEN-LAST:event_bt_exitActionPerformed

    private void bt_updateConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateConActionPerformed
        dispose();
        new updateCon_frame().setVisible(true);
    }//GEN-LAST:event_bt_updateConActionPerformed

    private void bt_disAllConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_disAllConActionPerformed
        new disAllCon_frame().setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_disAllConActionPerformed

    private void bt_srcConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_srcConActionPerformed
        new searchCon_frame().setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_srcConActionPerformed

    private void bt_remConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_remConActionPerformed
        dispose();
        new removeCon_frame().setVisible(true);
    }//GEN-LAST:event_bt_remConActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addCon;
    private javax.swing.JButton bt_disAllCon;
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_remCon;
    private javax.swing.JButton bt_srcCon;
    private javax.swing.JButton bt_updateCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
